env:
  node: true
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - off
  no-console:
    - off
  quotes:
    - error
    - single
    - allowTemplateLiterals: true    
  semi:
    - error
    - always
